export const tokens = {
  colors: {
    bgDark: "#0e0d0b",
    bgLight: "#faf8f5",
    panelDark: "#12110f",
    panelLight: "#f5f3f0",
    surfaceDark: "#1a1917",
    surfaceLight: "#edeae5",
    surfaceHoverDark: "#22211e",
    surfaceHoverLight: "#e5e2dd",
    textDark: "#f0ece4",
    textLight: "#1e1c19",
    mutedDark: "#9c968a",
    mutedLight: "#7a756d",
    faintDark: "#6b665e",
    faintLight: "#a9a49c",
    accentDark: "#b8a99a",
    accentLight: "#8a7d6e",
    successDark: "#8a9e8a",
    successLight: "#6a8a6a",
    errorDark: "#b87a72",
    errorLight: "#a05a52",
    priorityNoneDark: "#5a5854",
    priorityNoneLight: "#b0aba3",
    priorityLowDark: "#5a8ec2",
    priorityLowLight: "#4a7eb2",
    priorityMediumDark: "#c9a14d",
    priorityMediumLight: "#b8903a",
    priorityHighDark: "#c45a5a",
    priorityHighLight: "#b85050",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radii: {
    sm: 6,
    md: 10,
    lg: 14,
    full: 9999,
  },
  font: {
    sans: '-apple-system, BlinkMacSystemFont, "Segoe UI Variable", "HarmonyOS Sans SC", "MiSans", "Microsoft YaHei UI", sans-serif',
  },
} as const;

export type Tokens = typeof tokens;
